language: cpp
script:
- cd formatter_lib
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cd ..
- cd formatter_ex_lib
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cd ..
- cd hello_world_application
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cd ..
- cd solver_lib
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cd ..
- cd solver_application
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - mingw-w64
