language: cpp
script:
#- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
#- cmake --build _build
#- cmake --build _build --target install
- cd solver_application
- cmake .
- make
- cd ..
- cd hello_world_application
- cmake .
- make
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - mingw-w64
